const user = "user.png";
const wishlist = "wishlist.png";
const cart = "cart.png";
const search = "search.png";
const syltherine = "Syltherine.png";
const grifo = "grifo.png";
const leviosa = "leviosa.png";
const lolito = "lolito.png";
const muggo = "muggo.png";
const pinky = "Syltherine.png";
const potty = "potty.png";
const respira = "respira.png";
const trophy = "trophy.png";
const warranty = "warranty.png";
const shipping = "shipping.png";
const customer = "customer.png";

export const navLinks = [
  {
    id: "home",
    title: "Home",
    dest: "/",
  },
  {
    id: "shop",
    title: "Shop",
    dest: "/shop",
  },
  {
    id: "about",
    title: "About",
  },
  {
    id: "connect",
    title: "Connect",
  },
];

export const navMenu = [
  {
    id: "user",
    title: "user",
    icon: user,
  },
  {
    id: "search",
    title: "search",
    icon: search,
  },
  {
    id: "wishlist",
    title: "wishlist",
    icon: wishlist,
  },
  {
    id: "cart",
    title: "cart",
    icon: cart,
  },
];

export const products = [
  {
    id: "1",
    name: "Syltherine1",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "2",
    name: "Leviosa1",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "3",
    name: "Lolito1",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    desc: "Luxury big sofa",
  },
  {
    id: "4",
    name: "Respira1",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Outdoor bar table and stool",
  },
  {
    id: "5",
    name: "Grifo1",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    desc: "Night Lamp",
  },
  {
    id: "6",
    name: "Muggo1",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    desc: "Small mug",
  },
  {
    id: "7",
    name: "Pinky1",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    desc: "Cute bed set",
  },
  {
    id: "8",
    name: "Potty1",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Minimalist small pot",
  },
  {
    id: "9",
    name: "Syltherine2",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "10",
    name: "Leviosa2",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "11",
    name: "Lolito2",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    desc: "Luxury big sofa",
  },
  {
    id: "12",
    name: "Respira2",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Outdoor bar table and stool",
  },
  {
    id: "13",
    name: "Grifo2",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    desc: "Night Lamp",
  },
  {
    id: "14",
    name: "Muggo2",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    desc: "Small mug",
  },
  {
    id: "15",
    name: "Pinky2",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    desc: "Cute bed set",
  },
  {
    id: "16",
    name: "Potty2",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Minimalist small pot",
  },
  {
    id: "17",
    name: "Syltherine3",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "18",
    name: "Leviosa3",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "19",
    name: "Lolito3",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    desc: "Luxury big sofa",
  },
  {
    id: "20",
    name: "Respira3",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Outdoor bar table and stool",
  },
  {
    id: "21",
    name: "Grifo3",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    desc: "Night Lamp",
  },
  {
    id: "22",
    name: "Muggo3",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    desc: "Small mug",
  },
  {
    id: "23",
    name: "Pinky3",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    desc: "Cute bed set",
  },
  {
    id: "24",
    name: "Potty3",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Minimalist small pot",
  },
  {
    id: "25",
    name: "Syltherine4",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "26",
    name: "Leviosa4",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "27",
    name: "Lolito4",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    desc: "Luxury big sofa",
  },
  {
    id: "28",
    name: "Respira4",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Outdoor bar table and stool",
  },
  {
    id: "29",
    name: "Grifo4",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    desc: "Night Lamp",
  },
  {
    id: "30",
    name: "Muggo4",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    desc: "Small mug",
  },
  {
    id: "31",
    name: "Pinky4",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    desc: "Cute bed set",
  },
  {
    id: "32",
    name: "Potty4",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Minimalist small pot",
  },
  {
    id: "33",
    name: "Syltherine5",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "34",
    name: "Leviosa5",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "35",
    name: "Lolito5",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    desc: "Luxury big sofa",
  },
  {
    id: "36",
    name: "Respira5",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Outdoor bar table and stool",
  },
  {
    id: "37",
    name: "Grifo5",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    desc: "Night Lamp",
  },
  {
    id: "38",
    name: "Muggo5",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    desc: "Small mug",
  },
  {
    id: "39",
    name: "Pinky5",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    desc: "Cute bed set",
  },
  {
    id: "40",
    name: "Potty5",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Minimalist small pot",
  },
  {
    id: "41",
    name: "Syltherine6",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "42",
    name: "Leviosa6",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    desc: "Stylish cafe chair",
  },
  {
    id: "43",
    name: "Lolito6",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    desc: "Luxury big sofa",
  },
  {
    id: "44",
    name: "Respira6",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Outdoor bar table and stool",
  },
  {
    id: "45",
    name: "Grifo6",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    desc: "Night Lamp",
  },
  {
    id: "46",
    name: "Muggo6",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    desc: "Small mug",
  },
  {
    id: "47",
    name: "Pinky6",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    desc: "Cute bed set",
  },
  {
    id: "48",
    name: "Potty6",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    desc: "Minimalist small pot",
  },
  //   {
  //     id: uuidv4(),
  //     name: "Syltherine",
  //     img: "",
  //     disc: "30",
  //     price: 3500000,
  //     desc: "Stylish cafe chair",
  //   },
  //   {
  //     id: "1",
  //     name: "Syltherine",
  //     img: "",
  //     disc: "30",
  //     price: 3500000,
  //     desc: "Stylish cafe chair",
  //   },
];

export const offer = [
  { name: "High Quality", desc: "Crafted from top materials", icon: trophy },
  { name: "Warranty Protection", desc: "Over 2 years", icon: warranty },
  { name: "Free Shipping", desc: "Order over $150", icon: shipping },
  { name: "24/7 Support", desc: "Dedicated support", icon: customer },
];
