const user = "user.png";
const wishlist = "wishlist.png";
const cart = "cart.png";
const search = "search.png";
const syltherine = "Syltherine.png";
const grifo = "grifo.png";
const leviosa = "leviosa.png";
const lolito = "lolito.png";
const muggo = "muggo.png";
const pinky = "Syltherine.png";
const potty = "potty.png";
const respira = "respira.png";
const trophy = "trophy.png";
const warranty = "warranty.png";
const shipping = "shipping.png";
const customer = "customer.png";

export const navLinks = [
  {
    id: "home",
    title: "Home",
    dest: "/",
  },
  {
    id: "shop",
    title: "Shop",
    dest: "/shop",
  },
  {
    id: "about",
    title: "About",
  },
  {
    id: "connect",
    title: "Connect",
  },
];

export const navMenu = [
  {
    id: "user",
    title: "user",
    icon: user,
  },
  {
    id: "search",
    title: "search",
    icon: search,
  },
  {
    id: "wishlist",
    title: "wishlist",
    icon: wishlist,
  },
  {
    id: "cart",
    title: "cart",
    icon: cart,
  },
];

export const products = [
  {
    id: "1",
    name: "Syltherine",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "2",
    name: "Leviosa",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "3",
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: "4",
    name: "Respira",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: "5",
    name: "Grifo",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: "6",
    name: "Muggo",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: "7",
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: "8",
    name: "Potty",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: "9",
    name: "Syltherine",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "10",
    name: "Leviosa",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "11",
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: "12",
    name: "Respira",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: "13",
    name: "Grifo",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: "14",
    name: "Muggo",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: "15",
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: "16",
    name: "Potty",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: "17",
    name: "Syltherine",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "18",
    name: "Leviosa",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "19",
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: "20",
    name: "Respira",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: "21",
    name: "Grifo",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: "22",
    name: "Muggo",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: "23",
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: "24",
    name: "Potty",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: "25",
    name: "Syltherine",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "26",
    name: "Leviosa",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "27",
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: "28",
    name: "Respira",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: "29",
    name: "Grifo",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: "30",
    name: "Muggo",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: "31",
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: "32",
    name: "Potty",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: "33",
    name: "Syltherine",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "34",
    name: "Leviosa",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "35",
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: "36",
    name: "Respira",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: "37",
    name: "Grifo",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: "38",
    name: "Muggo",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: "39",
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: "40",
    name: "Potty",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: "41",
    name: "Syltherine",
    img: syltherine,
    disc: "0",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "42",
    name: "Leviosa",
    img: leviosa,
    disc: "0",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: "43",
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: "44",
    name: "Respira",
    img: respira,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: "45",
    name: "Grifo",
    img: grifo,
    disc: "0",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: "46",
    name: "Muggo",
    img: muggo,
    disc: "0",
    price: 150000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: "47",
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: "48",
    name: "Potty",
    img: potty,
    disc: "0",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => price - (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  //   {
  //     id: uuidv4(),
  //     name: "Syltherine",
  //     img: "",
  //     disc: "30",
  //     price: 3500000,
  //     desc: "Stylish cafe chair",
  //   },
  //   {
  //     id: "1",
  //     name: "Syltherine",
  //     img: "",
  //     disc: "30",
  //     price: 3500000,
  //     desc: "Stylish cafe chair",
  //   },
];

export const offer = [
  { name: "High Quality", desc: "Crafted from top materials", icon: trophy },
  { name: "Warranty Protection", desc: "Over 2 years", icon: warranty },
  { name: "Free Shipping", desc: "Order over $150", icon: shipping },
  { name: "24/7 Support", desc: "Dedicated support", icon: customer },
];
