import user from "../src/assets/icons/user.png";
import wishlist from "../src/assets/icons/wishlist.png";
import cart from "../src/assets/icons/cart.png";
import search from "../src/assets/icons/search.png";
import syltherine from "../src/assets/images/Syltherine.png";
import grifo from "../src/assets/images/grifo.png";
import leviosa from "../src/assets/images/leviosa.png";
import lolito from "../src/assets/images/lolito.png";
import muggo from "../src/assets/images/muggo.png";
import pinky from "../src/assets/images/Syltherine.png";
import potty from "../src/assets/images/potty.png";
import respira from "../src/assets/images/respira.png";
import trophy from "../src/assets/icons/trophy.png";
import warranty from "../src/assets/icons/warranty.png";
import shipping from "../src/assets/icons/shipping.png";
import customer from "../src/assets/icons/customer.png";
import { v4 as uuidv4 } from "uuid";

export const navLinks = [
  {
    id: "home",
    title: "Home",
    dest: "/",
  },
  {
    id: "shop",
    title: "Shop",
    dest: "/shop",
  },
  {
    id: "about",
    title: "About",
  },
  {
    id: "connect",
    title: "Connect",
  },
];

export const navMenu = [
  {
    id: "user",
    title: "user",
    icon: user,
  },
  {
    id: "search",
    title: "search",
    icon: search,
  },
  {
    id: "wishlist",
    title: "wishlist",
    icon: wishlist,
  },
  {
    id: "cart",
    title: "cart",
    icon: cart,
  },
];

export const products = [
  {
    id: uuidv4(),
    name: "Syltherine",
    img: syltherine,
    disc: "100",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Leviosa",
    img: leviosa,
    disc: "100",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: uuidv4(),
    name: "Respira",
    img: respira,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: uuidv4(),
    name: "Grifo",
    img: grifo,
    disc: "100",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: uuidv4(),
    name: "Muggo",
    img: muggo,
    disc: "100",
    price: 150000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: uuidv4(),
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: uuidv4(),
    name: "Potty",
    img: potty,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: uuidv4(),
    name: "Syltherine",
    img: syltherine,
    disc: "100",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Leviosa",
    img: leviosa,
    disc: "100",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: uuidv4(),
    name: "Respira",
    img: respira,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: uuidv4(),
    name: "Grifo",
    img: grifo,
    disc: "100",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: uuidv4(),
    name: "Muggo",
    img: muggo,
    disc: "100",
    price: 150000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: uuidv4(),
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: uuidv4(),
    name: "Potty",
    img: potty,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: uuidv4(),
    name: "Syltherine",
    img: syltherine,
    disc: "100",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Leviosa",
    img: leviosa,
    disc: "100",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: uuidv4(),
    name: "Respira",
    img: respira,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: uuidv4(),
    name: "Grifo",
    img: grifo,
    disc: "100",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: uuidv4(),
    name: "Muggo",
    img: muggo,
    disc: "100",
    price: 150000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: uuidv4(),
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: uuidv4(),
    name: "Potty",
    img: potty,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: uuidv4(),
    name: "Syltherine",
    img: syltherine,
    disc: "100",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Leviosa",
    img: leviosa,
    disc: "100",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: uuidv4(),
    name: "Respira",
    img: respira,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: uuidv4(),
    name: "Grifo",
    img: grifo,
    disc: "100",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: uuidv4(),
    name: "Muggo",
    img: muggo,
    disc: "100",
    price: 150000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: uuidv4(),
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: uuidv4(),
    name: "Potty",
    img: potty,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: uuidv4(),
    name: "Syltherine",
    img: syltherine,
    disc: "100",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Leviosa",
    img: leviosa,
    disc: "100",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: uuidv4(),
    name: "Respira",
    img: respira,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: uuidv4(),
    name: "Grifo",
    img: grifo,
    disc: "100",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: uuidv4(),
    name: "Muggo",
    img: muggo,
    disc: "100",
    price: 150000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: uuidv4(),
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: uuidv4(),
    name: "Potty",
    img: potty,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  {
    id: uuidv4(),
    name: "Syltherine",
    img: syltherine,
    disc: "100",
    price: 3500000,
    new: true,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Leviosa",
    img: leviosa,
    disc: "100",
    price: 2500000,
    new: false,
    category: "chair",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Stylish cafe chair",
  },
  {
    id: uuidv4(),
    name: "Lolito",
    img: lolito,
    disc: "50",
    price: 14000000,
    new: false,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Luxury big sofa",
  },
  {
    id: uuidv4(),
    name: "Respira",
    img: respira,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Outdoor bar table and stool",
  },
  {
    id: uuidv4(),
    name: "Grifo",
    img: grifo,
    disc: "100",
    price: 1500000,
    new: false,
    category: "lamp",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Night Lamp",
  },
  {
    id: uuidv4(),
    name: "Muggo",
    img: muggo,
    disc: "100",
    price: 150000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Small mug",
  },
  {
    id: uuidv4(),
    name: "Pinky",
    img: pinky,
    disc: "50",
    price: 14000000,
    new: false,
    category: "bed",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Cute bed set",
  },
  {
    id: uuidv4(),
    name: "Potty",
    img: potty,
    disc: "100",
    price: 500000,
    new: true,
    category: "sofa",
    discPr: (disc, price) => (parseInt(disc) * price) / 100,
    desc: "Minimalist small pot",
  },
  //   {
  //     id: uuidv4(),
  //     name: "Syltherine",
  //     img: "",
  //     disc: "30",
  //     price: 3500000,
  //     desc: "Stylish cafe chair",
  //   },
  //   {
  //     id: "1",
  //     name: "Syltherine",
  //     img: "",
  //     disc: "30",
  //     price: 3500000,
  //     desc: "Stylish cafe chair",
  //   },
];

export const offer = [
  { name: "High Quality", desc: "Crafted from top materials", icon: trophy },
  { name: "Warranty Protection", desc: "Over 2 years", icon: warranty },
  { name: "Free Shipping", desc: "Order over $150", icon: shipping },
  { name: "24/7 Support", desc: "Dedicated support", icon: customer },
];
